# Generated by Django 3.2 on 2021-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userbookrelation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_book',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
